# Generated by Django 5.1.1 on 2024-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='undefine'),
        ),
    ]
