# Generated by Django 5.1.1 on 2024-09-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=50),
        ),
    ]
